---
title: "Generalized Linear Model"
author: "Takeshi Kishiyama"
date: '`r format(Sys.time(), "%Y/%m/%d %H:%M")`'
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    cache = FALSE,
    warning = FALSE,
    width=6,
    fig.align='center',
    fig.pos='H',
    dev = c("png", "svg")
)
# knitr::opts_chunk$set(echo=FALSE)
library(DiagrammeR)
library(tidyverse)
library(lubridate)
library(magrittr)
library(ggplot2)
library(DT)
library(rmarkdown)
'%r+%' <- function(a,b) rbind(a,b)
library("dplyr")
library("stringr")
```

# はじめに

## 今日のテーマ

* R入門（関数型のアプローチ）
* **8章と9章**
* 10章
    
## 8章と9章

* 相関関係と因果関係の違い(交絡変数は触れたい)
* 線形回帰のパラメータ推定
* 線形回帰が解決できる／できない問題

## 相関関係と因果関係の違い

* 以下の２つのどちらが相関で因果？
    * 木の高さ体積の関係(図左)
    * 車の時速と停止距離の関係(図右)

```{r plot, fig.height=3}
par(mfrow=c(1,2))
plot(trees$Height, trees$Volume)
plot(cars$speed, cars$dist)
```

## なんで相関関係と因果関係の違いが大切なの？

* 結果が相関しているからと言って因果関係があるとは限らない
* 実験デザインで **交絡** が見つかるとしんどい

## 

## 因果関係のガイドライン

* Hill(1965)からピックアップ
    * A->Bの相関強い？ 
    * A->Bは時系列に沿ってる？
    * A->Bは他の知見と比べて妥当？
* 交絡は即死

## ここまでの参考書

* 因果推論

## 交絡

```{r}
grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica]
  Height; Volume; 木の種類や樹齢、環境など;

  # several 'edge' statements
  木の種類や樹齢、環境など -> Height
  木の種類や樹齢、環境など -> Volume

}
")
```


```{r}
head(cars)
head(trees)
plot(cars)
```

## 線形回帰のパラメータ推定

## 線形回帰が解決できる／できない問題
